---
id: AWCFAS
name: Asia
areaConfigurations:
- areaCode: "az"
  # Should be synchronized between Asia and Europe
  elections:
    national:
      dates:
        14: "2000-11-05"
        15: "2005-11-06"
        16: "2010-11-07"
        17: "2015-11-01"
        18: "2020-02-09"
        19: "2024-09-01"
        20: "≤2029-09"
    presidential:
      dates:
        5: "2003-10-15"
        6: "2008-10-15"
        7: "2013-10-09"
        8: "2018-04-11"
        9: "2024-02-07"
        10: "≈2031-02"
  translations:
    de: "Aserbaidschan"
    en: "Azerbaijan"
    eo: "Azerbajĝano"
    fr: "Azerbaïdjan"
    nl: "Azerbeidzjan"
    no: "Aserbajdsjan"
- areaCode: "bd"
  csvConfiguration:
    electoralListIds:
    - "BD202501"
    - "BD194101"
    - "BD197801"
    - "BD194901"
    - "BD198701"
    - "BD198601"
  elections:
    national:
      dates:
        19: "2001-10-01"
        20: "2008-12-29"
        21: "2014-01-05"
        22: "2018-12-30"
        23: "2024-01-07"
        24: "2026-02-12"
  translations:
    de: "Bangladesch"
    en: "Bangladesh"
    eo: "Bangladeŝo"
    fr: "Bangladesh"
    nl: "Bangladesh"
    no: "Bangladesh"
- areaCode: "bt"
  elections:
    national:
      dates:
        1: "2008-03-24"
        2: "2013-05-31+2013-07-13"
        3: "2018-09-15+2018-10-18"
        4: "2023-11-30+2024-01-09"
        5: "≤2029-02"
  translations:
    de: "Bhutan"
    en: "Bhutan"
    eo: "Butano"
    fr: "Bhoutan"
    nl: "Bhutan"
    no: "Bhutan"
- areaCode: "ge"
  # Should be synchronized between Asia and Europe
  csvConfiguration:
    electoralListIds:
    - "GE201201"
    - "GE200101"
    - "GE201701"
    - "GE199501"
    - "GE201202"
    - "GE200802"
    - "GE202001"
    - "GE201601"
    - "GE201901"
    - "GE201702"
    - "GE201602"
    - "GE012"
    - "GE013"
    - "GE014"
    - "GE015"
    - "GE016"
    - "GE017"
    - "GE018"
    - "GE014+GE015"
    - "GE019"
    - "GE020"
    - "GE021"
    - "GE200901"
    - "GE200801"
    - "GE024"
    - "GE197801"
  elections:
    national:
      dates:
        17: "2003-11-02"
        18: "2004-03-28"
        19: "2008-05-21"
        20: "2012-10-01"
        21: "2016-10-08+2016-10-30"
        22: "2020-10-31+2020-11-21"
        23: "2024-10-26"
        24: "≤2028-10"
  translations:
    de: "Georgien"
    en: "Georgia"
    eo: "Kartvelio"
    fr: "Géorgie"
    nl: "Georgië"
    no: "Georgia"
- areaCode: "hk"
  csvConfiguration:
    electoralListIds:
    - "HK199401"
    - "HK199201"
    - "HK199601"
    - "HK199301"
    - "HK200301"
    - "HK199001"
    - "HK198601"
    - "HK200601"
    - "HK200602"
    - "HK194801"
    - "HK201101"
    - "HK201102"
    - "HK201103"
    - "HK200602+HK201102"
    - "HK201001+HK201201+HK201401"
    - "HK201202"
    - "HK201601"
    - "HK201602"
  elections:
    national:
      dates:
        7: "2000-09-10"
        8: "2004-09-12"
        9: "2008-09-07"
        10: "2012-09-09"
        11: "2016-09-04"
        12: "2021-12-19"
        13: "2025-12-07"
        14: "≤2029-12"
  translations:
    de: "Hongkong"
    en: "Hong Kong"
    eo: "Honkongo"
    fr: "Hong Kong"
    nl: "Hongkong"
    no: "Hongkong"
- areaCode: "iq"
  elections:
    national:
      dates:
        22: "2000-03-27"
        23: "2005-01-30"
        24: "2005-12-15"
        25: "2010-03-07"
        26: "2014-04-30"
        27: "2018-05-12"
        28: "2021-10-10"
        29: "2025-11-11"
        30: "≤2029-11"
  translations:
    de: "Irak"
    en: "Iraq"
    eo: "Irako"
    fr: "Irak"
    nl: "Irak"
    no: "Irak"
- areaCode: "kg"
  csvConfiguration:
    electoralListIds:
    - "KG199201"
    - "KG199301"
    - "KG200601"
    - "KG201001"
    - "KG200701"
    - "KG199901"
    - "KG200602"
    - "KG199902"
    - "KG201201"
    - "KG201101"
    - "KG201202"
    - "KG202101"
    - "KG201901"
  elections:
    national:
      dates:
        14: "2000-02-20"
        15: "2005-02-27+2005-03-13"
        16: "2007-12-16"
        17: "2010-10-10"
        18: "2015-10-04"
        19: "2020-10-04"
        20: "2021-11-28"
        24: "2025-11-30"
        25: "≤2029-11"
    presidential:
      dates:
        3: "2000-10-29"
        4: "2005-07-10"
        5: "2009-07-23"
        6: "2011-10-30"
        7: "2017-10-15"
        8: "2021-01-10"
        9: "≈2027-01"
  translations:
    de: "Kirgisistan"
    en: "Kyrgyzstan"
    eo: "Kirgizio"
    fr: "Kirghizistan"
    nl: "Kirgizië"
    no: "Kirgisistan"
- areaCode: "kr"
  elections:
    national:
      dates:
        17: "2000-04-13"
        18: "2004-04-15"
        19: "2008-04-09"
        20: "2012-04-11"
        21: "2016-04-13"
        22: "2020-04-15"
        23: "2024-04-10"
        24: "≤2028-04-12"
    presidential:
      dates:
        17: "2002-12-19"
        18: "2007-12-19"
        19: "2012-12-19"
        20: "2017-05-09"
        21: "2022-03-09"
        22: "2025-06-03"
        23: "≈2030-06"
  translations:
    de: "Südkorea"
    en: "South Korea"
    eo: "Sud-Koreio"
    fr: "Corée du Sud"
    nl: "Zuid-Korea"
    no: "Sør-Korea"
- areaCode: "kz"
  # Should be synchronized between Asia and Europe
  elections:
    national:
      dates:
        4: "2004-09-19+2004-10-03"
        5: "2007-08-18"
        6: "2012-01-15"
        7: "2016-03-20"
        8: "2021-01-10"
        9: "2023-03-19"
        10: "≤2028-03"
    presidential:
      dates:
        3: "2005-12-04"
        4: "2011-04-03"
        5: "2015-04-26"
        6: "2019-06-09"
        7: "2022-11-20"
        8: "≈2029-11"
  translations:
    de: "Kasachstan"
    en: "Kazakhstan"
    eo: "Kazaĥio"
    fr: "Kazakhstan"
    nl: "Kazachstan"
    no: "Kasakhstan"
- areaCode: "la"
  elections:
    national:
      dates:
        13: "2002-02-24"
        14: "2006-04-30"
        15: "2011-04-30"
        16: "2016-03-20"
        17: "2021-02-21"
        18: "2026-02-22"
  translations:
    de: "Laos"
    en: "Laos"
    eo: "Laoso"
    fr: "Laos"
    nl: "Laos"
    no: "Laos"
- areaCode: "mm"
  elections:
    national:
      dates:
        15: "2010-11-07"
        16: "2015-11-08"
        17: "2020-11-08"
        18: "2025-12-28+2026-01-11+2026-01-25"
  translations:
    de: "Myanmar"
    en: "Myanmar"
    eo: "Birmo"
    fr: "Birmanie"
    nl: "Myanmar"
    no: "Myanmar"
- areaCode: "mo"
  elections:
    national:
      dates:
        8: "2001-09-23"
        9: "2005-09-25"
        10: "2009-09-20"
        11: "2013-09-15"
        12: "2017-09-17"
        13: "2021-09-12"
        14: "2025-09-14"
        15: "≤2029-09"
  translations:
    de: "Macau"
    en: "Macau"
    eo: "Makao"
    fr: "Macao"
    nl: "Macau"
    no: "Macao"
- areaCode: "mv"
  elections:
    national:
      dates:
        8: "2005-01-22"
        9: "2009-05-09"
        10: "2014-03-22"
        11: "2019-04-06"
        12: "2024-04-21"
        13: "≤2029-05"
    presidential:
      dates:
        9: "2003-10-17"
        10: "2008-10-08+2008-10-28"
        11: "(2013-09-07)+2013-11-09+2013-11-16"
        12: "2018-09-23"
        13: "2023-09-09+2023-09-30"
        14: "≈2028-09"
  translations:
    de: "Malediven"
    en: "Maldives"
    eo: "Maldivoj"
    fr: "Maldives"
    nl: "Malediven"
    no: "Maldivene"
- areaCode: "np"
  csvConfiguration:
    electoralListIds:
    - "NP195001"
    - "NP199101"
    - "NP199401"
  elections:
    national:
      dates:
        8: "2008-04-10"
        9: "2013-11-19"
        10: "2017-11-26+2017-12-07"
        11: "2022-11-20"
        12: "2026-03-05"
  translations:
    de: "Nepal"
    en: "Nepal"
    eo: "Nepalo"
    fr: "Népal"
    nl: "Nepal"
    no: "Nepal"
- areaCode: "ph"
  elections:
    national:
      dates:
        28: "2001-05-14"
        29: "2004-05-10"
        30: "2007-05-14"
        31: "2010-05-10"
        32: "2013-05-13"
        33: "2016-05-09"
        34: "2019-05-13"
        35: "2022-05-09"
        36: "2025-05-12"
        37: "≤2028-05"
    presidential:
      dates:
        14: "2004-05-10"
        15: "2010-05-10"
        16: "2016-05-09"
        17: "2022-05-09"
        18: "2028-05-13"
  translations:
    de: "Philippinen"
    en: "Philippines"
    eo: "Filipinoj"
    fr: "Philippines"
    nl: "Filipijnen"
    no: "Filippinene"
- areaCode: "pk"
  csvConfiguration:
    electoralListIds:
    - "PK199601"
    - "PK196701"
    - "PK199201"
    - "PK201601"
    - "PK201701"
    - "PK198601"
    - "PK201501"
    - "PK194501"
    - "PK201702"
    - "PK194701"
  elections:
    national:
      dates:
        14: "2002-10-10"
        15: "2008-02-18"
        16: "2013-05-11"
        17: "2018-07-25"
        18: "2024-02-08"
        19: "≤2029-05-28"
  translations:
    de: "Pakistan"
    en: "Pakistan"
    eo: "Pakistano"
    fr: "Pakistan"
    nl: "Pakistan"
    no: "Pakistan"
- areaCode: "ru"
  # Should be synchronized between Asia and Europe
  csvConfiguration:
    electoralListIds:
    - "RU001"
    - "RU002"
    - "RU003"
    - "RU004"
    - "RU007"
    - "RU005"
    - "RU006"
    - "RU008"
    - "RU009"
    - "RU010"
  elections:
    national:
      dates:
        0: "≤2026-09-20"
    presidential:
      dates:
        3: "2000-03-26"
        4: "2004-03-13"
        5: "2008-03-02"
        6: "2012-03-04"
        7: "2018-03-18"
#        8: "2024-03-15/2024-03-16/2024-03-17"
        8: "2024-03-17"
        9: "≈2030-03"
  pollingFirmsNotIncluded:
    "ВЦИОМ": fundedByAnAuthoritarianGovernment
    "ФОМ": fundedByAnAuthoritarianGovernment
  translations:
    de: "Russland"
    en: "Russia"
    eo: "Rusio"
    fr: "Russie"
    nl: "Rusland"
    no: "Russland"
- areaCode: "sg"
  elections:
    national:
      dates:
        14: "2001-11-03"
        15: "2006-05-06"
        16: "2011-05-07"
        17: "2015-09-11"
        18: "2020-07-10"
        19: "2025-05-03"
        20: "≤2030-05"
    presidential:
      dates:
        3: "2005-08-17"
        4: "2011-08-27"
        5: "2017-09-13"
        6: "2023-09-01"
        7: "≈2029-09"
  translations:
    de: "Singapur"
    en: "Singapore"
    eo: "Singapuro"
    fr: "Singapour"
    nl: "Singapore"
    no: "Singapore"
- areaCode: "th"
  elections:
    national:
      dates:
        20: "2001-01-06"
        21: "2005-02-06"
        22: "2006-04-02"
        23: "2007-12-23"
        24: "2011-07-03"
        25: "2014-02-02"
        26: "2019-03-24"
        27: "2023-05-14"
        28: "2026-02-08"
  translations:
    de: "Thailand"
    en: "Thailand"
    eo: "Thajlando"
    fr: "Thaïlande"
    nl: "Thailand"
    no: "Thailand"
- areaCode: "tj"
  elections:
    national:
      dates:
        14: "2000-02-27"
        15: "2005-02-27+2005-03-15"
        16: "2010-02-28+2010-03-14"
        17: "2015-03-01"
        18: "2020-03-01"
        19: "2025-03-02"
        20: "≤2030-03"
    presidential:
      dates:
        4: "2006-11-06"
        5: "2013-11-06"
        6: "2020-10-11"
        7: "⪅2027-10"
  translations:
    de: "Tadschikistan"
    en: "Tajikistan"
    eo: "Taĝikio"
    fr: "Tadjikistan"
    nl: "Tadzjikistan"
    no: "Tadsjikistan"
- areaCode: "tr"
  # Should be synchronized between Asia and Europe
  csvConfiguration:
    electoralListIds:
    - "TR001"
    - "TR002"
    - "TR004"
    - "TR003"
    - "TR005"
    - "TR006"
    - "TR008"
    - "TR007"
    - "TR010"
    - "TR009"
    - "TR011"
    - "TR012"
    - "TR013"
    - "TR014"
    - "TR015"
    - "TR016"
    - "TR017"
    - "TR018"
  elections:
    national:
      dates:
        21: "2002-11-03"
        22: "2007-07-22"
        23: "2011-06-12"
        24: "2015-07-07"
        25: "2015-11-01"
        26: "2018-06-24"
        27: "2023-05-14"
        28: "≤2028-05-07"
    presidential:
      dates:
        1: "2014-08-10"
        2: "2018-06-24"
        3: "2023-05-14+2023-05-28"
        4: "≤2028-05-07"
  translations:
    de: "Türkei"
    en: "Turkey"
    eo: "Turkio"
    fr: "Turquie"
    nl: "Turkije"
    no: "Tyrkia"
- areaCode: "tw"
  elections:
    national:
      dates:
        11: "2001-12-01"
        12: "2004-12-11"
        13: "2008-01-12"
        14: "2012-01-14"
        15: "2016-01-16"
        16: "2020-01-11"
        17: "2024-01-13"
        18: "≤2028-01"
    presidential:
      dates:
        2: "2000-03-18"
        3: "2004-03-20"
        4: "2008-03-22"
        5: "2012-01-14"
        6: "2016-01-16"
        7: "2020-01-11"
        8: "2024-01-13"
        9: "≈2028-01"
  translations:
    de: "Taiwan"
    en: "Taiwan"
    eo: "Tajvano"
    fr: "Taïwan"
    nl: "Taiwan"
    no: "Taiwan"
- areaCode: "vn"
  elections:
    national:
      dates:
        6: "2002-05-19"
        7: "2007-05-20"
        8: "2011-05-22"
        9: "2016-05-22"
        10: "2021-05-23"
        11: "2026-03-15"
  translations:
    de: "Vietnam"
    en: "Vietnam"
    eo: "Vjetnamio"
    fr: "Vietnam"
    nl: "Vietnam"
    no: "Vietnam"
widgetsConfiguration:
  tableFontFamily: "Alegreya Sans,'Helvetica Neue',Helvetica,sans-serif"
  tableStylesheets:
  - https://fonts.googleapis.com/css?family=Alegreya+Sans%3A400%2C700%2C400italic%2C700italic%2C600%2C600italic%7CAlegreya+Sans%3A400%2C500%2C600%2C700%2C400italic%2C700italic&ver=1
  - https://europeelects.eu/wp-content/themes/chaplin/style.css?ver=2.6.7
